Handle SIGPIPE
When somebody parses the output of webvulnscan and has read enough (for example because only one line is necessary, see #31), Python by default crashes with an unsightly

    <long traceback>
    IOError: [Errno 32] Broken pipe

Instead, webvulnscan should simply exit; that's the default action for the signal anyway.
To test, try

    python -m webvulnscan http://localhost:8666/ -v | head -n 1